server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RickyOrtega/gamebox
          clone-on-start: false

management:
  endpoints:
    web:
      exposure:
        include: '*'